// flask_backend/backends/flask/src/MyAngularApp/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'MyAngularApp';
  onClickMe() {
    alert("Hello from AppFizzle!")
  }
}

<div style="text-align:center">
    <h1>Welcome to AppFizzle!</h1>
    <p>This is a basic Angular application.</p>
  <button (click)="onClickMe()">Click Me</button>
</div>

// flask_backend/frontends/react/generics/src/App.js
import './App.css';
import logo from './logo.svg';

function App() {
  // Function to handle button click
  const handleClick = () => {
    alert('Hello from AppFizzle!');
  };

  return (
    <div className="App">
      <header className="App-header">
      <img src={logo} className="App-logo" alt="logo" />

        <h1>Welcome to AppFizzle!</h1>
        <p>This is a basic React application.</p>
        {/* Button with click event handler */}
        <button id="clickMeBtn" onClick={handleClick}>Click Me</button>
      </header>
    </div>
  );
}

export default App;
